In [4]:
import pandas as pd

df = pd.read_excel('PRE2013.xlsx')
df

,Day,Hour,NEE,LE,H,Rg,Tair,Tsoil,rH,VPD,Ustar
0,--,--,umolm-2s-1,Wm-2,Wm-2,Wm-2,degC,degC,%,hPa,ms-1
1,1,0.5,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
2,1,1,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
3,1,1.5,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
4,1,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
...,...,...,...,...,...,...,...,...,...,...,...
17516,365,22,1.317576,-2.113446,-4.222929,-1.650576,24.11463,29.31614,84.10452,4.693953,0.341839
17517,365,22.5,0.234337,-17.096266,1.974016,-2.103711,23.99404,29.22911,86.27364,4.024035,0.374856
17518,365,23,-0.224384,-10.566178,-5.732129,-2.074909,23.87093,29.14392,87.43149,3.657315,0.360931
17519,365,23.5,1.597789,-9.588491,-4.534221,-2.309459,23.6706,29.05899,88.96199,3.173296,0.431153
17520,365,24,1.426377,-5.17779,-6.128092,-1.824817,23.67208,28.97242,89.76054,2.943986,0.366103